# CMake generated Testfile for 
# Source directory: /home/zizo/omplapp/ompl/tests
# Build directory: /home/zizo/omplapp/ompl/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_adjacency_list "/home/zizo/omplapp/bin/test_adjacency_list")
set_tests_properties(test_adjacency_list PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;15;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_heap "/home/zizo/omplapp/bin/test_heap")
set_tests_properties(test_heap PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;16;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_grid "/home/zizo/omplapp/bin/test_grid")
set_tests_properties(test_grid PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;17;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_gridb "/home/zizo/omplapp/bin/test_gridb")
set_tests_properties(test_gridb PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;18;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_nearestneighbors "/home/zizo/omplapp/bin/test_nearestneighbors")
set_tests_properties(test_nearestneighbors PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;19;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_pdf "/home/zizo/omplapp/bin/test_pdf")
set_tests_properties(test_pdf PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;25;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_random "/home/zizo/omplapp/bin/test_random")
set_tests_properties(test_random PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;28;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_halton_sampling "/home/zizo/omplapp/bin/test_halton_sampling")
set_tests_properties(test_halton_sampling PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;35;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_state_operations "/home/zizo/omplapp/bin/test_state_operations")
set_tests_properties(test_state_operations PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;36;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_state_spaces "/home/zizo/omplapp/bin/test_state_spaces")
set_tests_properties(test_state_spaces PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;37;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_state_storage "/home/zizo/omplapp/bin/test_state_storage")
set_tests_properties(test_state_storage PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;38;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_ptc "/home/zizo/omplapp/bin/test_ptc")
set_tests_properties(test_ptc PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;39;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_planner_data "/home/zizo/omplapp/bin/test_planner_data")
set_tests_properties(test_planner_data PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;40;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_2denvs_geometric "/home/zizo/omplapp/bin/test_2denvs_geometric")
set_tests_properties(test_2denvs_geometric PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;43;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_2dmap_geometric_simple "/home/zizo/omplapp/bin/test_2dmap_geometric_simple")
set_tests_properties(test_2dmap_geometric_simple PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;44;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_2dmap_ik "/home/zizo/omplapp/bin/test_2dmap_ik")
set_tests_properties(test_2dmap_ik PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;45;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_2dcircles_opt_geometric "/home/zizo/omplapp/bin/test_2dcircles_opt_geometric")
set_tests_properties(test_2dcircles_opt_geometric PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;46;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_2dpath_simplifying "/home/zizo/omplapp/bin/test_2dpath_simplifying")
set_tests_properties(test_2dpath_simplifying PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;47;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_constraint_sphere "/home/zizo/omplapp/bin/test_constraint_sphere")
set_tests_properties(test_constraint_sphere PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;50;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_2dmap_control "/home/zizo/omplapp/bin/test_2dmap_control")
set_tests_properties(test_2dmap_control PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;53;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_planner_data_control "/home/zizo/omplapp/bin/test_planner_data_control")
set_tests_properties(test_planner_data_control PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;54;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
add_test(test_experience_planning "/home/zizo/omplapp/bin/test_experience_planning")
set_tests_properties(test_experience_planning PROPERTIES  _BACKTRACE_TRIPLES "/home/zizo/omplapp/ompl/CMakeModules/OMPLUtils.cmake;10;add_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;57;add_ompl_test;/home/zizo/omplapp/ompl/tests/CMakeLists.txt;0;")
subdirs("regression_tests")
